# Generated by Django 5.2.8 on 2025-12-06 02:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='ativo',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='department',
            name='membro',
        ),
        migrations.AddField(
            model_name='department',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='member_department', to=settings.AUTH_USER_MODEL, verbose_name='Membros'),
        ),
    ]
