# Generated by Django 5.2.8 on 2025-12-06 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_rename_ativo_department_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='member',
            new_name='members',
        ),
    ]
