# Generated by Django 5.2.8 on 2025-12-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título da reunião')),
                ('date', models.DateTimeField(verbose_name='Data e hora')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Pauta / Descrição')),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
                'ordering': ['-date'],
            },
        ),
    ]
